// AddStudentViewModel.cs
// ViewModel for AddStudentPage. Uses CommunityToolkit.Mvvm source generators for
// - ObservableObject base
// - [ObservableProperty] to auto-generate properties + change notification
// - AsyncRelayCommand for async commands bound from XAML

using CommunityToolkit.Mvvm.ComponentModel;   // ObservableObject, [ObservableProperty]
using CommunityToolkit.Mvvm.Input;            // AsyncRelayCommand, IAsyncRelayCommand
using MinistryTracker.Data;                   // DataService (our SQLite service)
using MinistryTracker.Models;                 // Student model
using MinistryTracker.Models.Enums;           // InitialCallType, StudentStatus
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinistryTracker.ViewModels
{
    /// <summary>
    /// DI-friendly ViewModel for adding a new Student.
    /// Notes:
    /// - The constructor requires DataService (provided by DI).
    /// - Properties are generated by the MVVM Toolkit via [ObservableProperty].
    /// - SaveCommand invokes SaveStudentAsync() to persist data then navigates back.
    /// </summary>
    public partial class AddStudentViewModel : ObservableObject
    {
        /// <summary>
        /// Data access service (SQLite via sqlite-net-pcl). Injected.
        /// </summary>
        private readonly DataService _data;

        /// <summary>
        /// Constructor called by the DI container.
        /// </summary>
        /// <param name="data">Injected DataService instance.</param>
        public AddStudentViewModel(DataService data)
        {
            _data = data ?? throw new ArgumentNullException(nameof(data));

            // Create the async command bound from XAML: Command="{Binding SaveCommand}"
            SaveCommand = new AsyncRelayCommand(SaveStudentAsync);
        }

        // --------------------------------------------------------------------
        // Properties bound from XAML (auto-generated getter/setter + OnPropertyChanged)
        // The backing field names are: name, callType, firstContactDate, preferredLanguage.
        // The generated public properties are: Name, CallType, FirstContactDate, PreferredLanguage.
        // --------------------------------------------------------------------

        [ObservableProperty]
        private string name = string.Empty;               // Required

        [ObservableProperty]
        private InitialCallType callType;                 // Required (enum)

        [ObservableProperty]
        private DateTime firstContactDate = DateTime.Today; // Required (defaults to today)

        [ObservableProperty]
        private string? preferredLanguage;                // Optional

        /// <summary>
        /// ItemsSource for the Initial Call Type <Picker>.
        /// Binding in XAML: ItemsSource="{Binding CallTypeValues}" SelectedItem="{Binding CallType}"
        /// </summary>
        public List<InitialCallType> CallTypeValues =>
            Enum.GetValues(typeof(InitialCallType)).Cast<InitialCallType>().ToList();

        /// <summary>
        /// Command bound to the Save button.
        /// </summary>
        public IAsyncRelayCommand SaveCommand { get; }

        /// <summary>
        /// Validates inputs, creates a Student, saves it via DataService, and navigates back.
        /// </summary>
        private async Task SaveStudentAsync()
        {
            // Basic validation: Name is required
            if (string.IsNullOrWhiteSpace(Name))
            {
                await Application.Current.MainPage.DisplayAlert("Missing Info", "Name is required.", "OK");
                return;
            }

            // Map VM properties to the data model
            var student = new Student
            {
                Name = Name.Trim(),
                CallType = CallType,
                FirstContactDate = FirstContactDate,
                PreferredLanguage = PreferredLanguage,
                Status = StudentStatus.Active,
                IsDeleted = false
            };

            // Persist and provide simple UX flow
            var rows = await _data.AddStudentAsync(student);
            if (rows > 0)
            {
                // Success: navigate back to the list
                await Application.Current.MainPage.Navigation.PopAsync();
            }
            else
            {
                await Application.Current.MainPage.DisplayAlert("Error", "Failed to add student. Please try again.", "OK");
            }
        }
    }
}
