using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MinistryTracker.Data;
using MinistryTracker.Models;
using MinistryTracker.Models.Enums;

namespace MinistryTracker.ViewModels
{
    public partial class EditStudentViewModel : ObservableObject
    {
        private readonly DataService _data;

        public EditStudentViewModel(DataService data)
        {
            _data = data;
        }

        // Properties generated by source generators
        [ObservableProperty] private int studentId;
        [ObservableProperty] private string name = string.Empty;
        [ObservableProperty] private InitialCallType callType;
        [ObservableProperty] private DateTime firstContactDate;

        // Called by the page after construction
        public void Load(Student student)
        {
            StudentId = student.StudentId;
            Name = student.Name;
            CallType = student.CallType;
            FirstContactDate = student.FirstContactDate;
        }

        [RelayCommand]
        private async Task SaveAsync()
        {
            var updated = new Student
            {
                StudentId = StudentId,
                Name = Name,
                CallType = CallType,
                FirstContactDate = FirstContactDate
            };

            await _data.UpdateStudentAsync(updated);
            await Shell.Current.GoToAsync("..");
        }
    }
}
