// ---------------------------------------------------------------------------------------------------------------------
// SettingsViewModel.cs
// ViewModel for Settings page (Diagnostics + Dev Seeding).
// - CancellationToken support so long-running DB work can be cancelled
// - Keeps UI responsive (IsBusy + timeouts) without calling UI APIs directly
// - Publishes Ui* messages; the View (XAML.cs) renders Toast/Snackbar/Alert/Confirm
// - Broadcasts lightweight messages so other VMs can refresh after reset/seed
// ---------------------------------------------------------------------------------------------------------------------

using CommunityToolkit.Mvvm.Input;
using CommunityToolkit.Mvvm.ComponentModel;            // [ObservableProperty]
                // [RelayCommand]
using CommunityToolkit.Mvvm.Messaging;                 // WeakReferenceMessenger
using MinistryTracker.Data;
using MinistryTracker.ViewModels.Messages;

namespace MinistryTracker.ViewModels
{
    public partial class SettingsViewModel : ObservableObject
    {
        private readonly DataService _data;
        [RelayCommand]
        private void HideHealth() => HealthExpanded = false;
         
        // Single active operation CTS; new operation cancels the previous one
        private CancellationTokenSource? _activeCts;

        // Bindables (XAML)
        [ObservableProperty] private bool isBusy;
        [ObservableProperty] private string dbHealthText = string.Empty;
        [ObservableProperty] private bool healthExpanded; // collapsed by default; expands after health loads

        public SettingsViewModel(DataService data) => _data = data;

        // -------------------------------------------------------------------------------------------------------------
        // Helpers: manage a single active operation with cancellation + busy state
        // -------------------------------------------------------------------------------------------------------------

        /// <summary>Cancels any in-flight operation, creates a fresh CTS, and toggles IsBusy.</summary>
        private CancellationToken StartOperation()
        {
            _activeCts?.Cancel();
            _activeCts?.Dispose();
            _activeCts = new CancellationTokenSource();

            IsBusy = true;
            return _activeCts.Token;
        }

        /// <summary>Ends the active operation and clears Busy state. Always call inside a 'finally' block.</summary>
        private void EndOperation() => IsBusy = false;

        /// <summary>Call this if the page is being navigated away / disposed.</summary>
        public void CancelActiveOperation()
        {
            _activeCts?.Cancel();
            _activeCts?.Dispose();
            _activeCts = null;
            IsBusy = false;
        }

        // -------------------------------------------------------------------------------------------------------------
        // COMMANDS (wired in XAML as *Command properties generated by [RelayCommand])
        // -------------------------------------------------------------------------------------------------------------

        /// <summary>
        /// Insert a small, deterministic set of Students + Visits if empty.
        /// Does NOT overwrite unless you later call the Reset+Seed command.
        /// </summary>
        [RelayCommand(AllowConcurrentExecutions = false)]
        private async Task SeedDemoData()
        {
            if (IsBusy) return;
            var ct = StartOperation();

            try
            {
                await _data.SeedDevDataFromDiagnosticsAsync(force: false, ct).ConfigureAwait(false);
                WeakReferenceMessenger.Default.Send(new UiToastMessage("✅ Demo data inserted (if empty)."));

                // Notify listeners (Dashboard / Students) to refresh
                WeakReferenceMessenger.Default.Send(new DataSeededMessage(DateTime.UtcNow));
            }
            catch (OperationCanceledException)
            {
                // User started another op or navigated away—silently ignore
            }
            catch (Exception ex)
            {
                WeakReferenceMessenger.Default.Send(new UiAlertMessage("Seeding failed", ex.Message));
            }
            finally
            {
                EndOperation();
            }
        }

        /// <summary>
        /// Wipe local DB, recreate schema, seed demo data, and checkpoint WAL so
        /// both ORM + fresh read-only connections see the same data immediately.
        /// </summary>
        [RelayCommand(AllowConcurrentExecutions = false)]
        private async Task ResetAndSeed()
        {
            if (IsBusy) return;

            // Ask the View to confirm (MVVM-pure). Await the user's choice via TCS callback.
            var tcs = new TaskCompletionSource<bool>();
            WeakReferenceMessenger.Default.Send(new UiConfirmMessage(
                title: "Reset Database",
                message: "This will wipe local data and recreate the DB, then seed demo data.\nContinue?",
                setResult: confirmed => tcs.TrySetResult(confirmed),
                accept: "Yes",
                cancel: "No"));

            var proceed = await tcs.Task.ConfigureAwait(false);
            if (!proceed) return;

            var ct = StartOperation();
            try
            {
                await _data.ResetAndSeedFromDiagnosticsAsync(ct).ConfigureAwait(false);

                // Toast in the View
                WeakReferenceMessenger.Default.Send(new UiToastMessage("Reset + seed complete"));

                // Ask View to show a snackbar that, when pressed, triggers ShowDbHealth
                WeakReferenceMessenger.Default.Send(
                    new UiSnackbarMessage("🧹 Reset + Seed complete.", "View health", UiSnackbarAction.ShowDbHealth));

                // Broadcast so dashboards/lists repopulate
                WeakReferenceMessenger.Default.Send(new DatabaseResetMessage(DateTime.UtcNow));
                WeakReferenceMessenger.Default.Send(new DataSeededMessage(DateTime.UtcNow));
            }
            catch (OperationCanceledException)
            {
                // user cancelled / navigated away — ignore
            }
            catch (Exception ex)
            {
                WeakReferenceMessenger.Default.Send(new UiAlertMessage("Reset failed", ex.Message));
            }
            finally
            {
                EndOperation();
            }
        }

        /// <summary>
        /// Quick health snapshot:
        /// - counts via ORM (mapping-safe)
        /// - fast path PRAGMA (skips deep integrity scan unless you opt-in)
        /// - table list + orphaned visits
        /// Writes text to DbHealthText (bound to the XAML Editor) and expands the card.
        /// </summary>
        [RelayCommand(AllowConcurrentExecutions = false)]
        private async Task ShowDbHealth()
        {
            if (IsBusy) return;
            var ct = StartOperation();

            try
            {
                // Give the DB a short breath if another op just completed
                await Task.Delay(150, ct);

                // Put a guard around long I/O so the button never feels stuck
                using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(8));
                using var linked = CancellationTokenSource.CreateLinkedTokenSource(ct, timeout.Token);

                var health = await _data.GetDbHealthAsync(deep: false, linked.Token).ConfigureAwait(false);
                DbHealthText = health.ToString();

                // Expand the card after a successful fetch
                HealthExpanded = true;

                WeakReferenceMessenger.Default.Send(new UiToastMessage("DB health updated"));
            }
            catch (OperationCanceledException)
            {
                // Timeout or user cancellation: be quiet, keep UX calm
                if (!ct.IsCancellationRequested)
                {
                    DbHealthText = "DB health timed out. Try again.";
                    WeakReferenceMessenger.Default.Send(new UiToastMessage("Health check timed out"));
                }
            }
            catch (Exception ex)
            {
                DbHealthText = $"Health check failed:\n{ex.Message}";
                WeakReferenceMessenger.Default.Send(new UiAlertMessage("Health check failed", ex.Message));
            }
            finally
            {
                EndOperation();
            }
        }

        // -------------------------------------------------------------------------------------------------------------
        // Lightweight messages any ViewModel can listen to for auto-refresh (Dashboard, Students, etc.)
        // Usage in other VMs:
        //     WeakReferenceMessenger.Default.Register<DatabaseResetMessage>(this, (_, __) => LoadAsync());
        //     WeakReferenceMessenger.Default.Register<DataSeededMessage>(this,  (_, __) => LoadAsync());
        // -------------------------------------------------------------------------------------------------------------

        public sealed class DatabaseResetMessage : CommunityToolkit.Mvvm.Messaging.Messages.ValueChangedMessage<DateTime>
        {
            public DatabaseResetMessage(DateTime whenUtc) : base(whenUtc) { }
        }

        public sealed class DataSeededMessage : CommunityToolkit.Mvvm.Messaging.Messages.ValueChangedMessage<DateTime>
        {
            public DataSeededMessage(DateTime whenUtc) : base(whenUtc) { }
        }
    }
}
