<Project>
  <PropertyGroup>
    <TestTempPath Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(TEMP)\MinistryTracker.Tests</TestTempPath>
    <TestTempPath Condition="!$([MSBuild]::IsOSPlatform('Windows'))">/tmp/MinistryTracker.Tests</TestTempPath>
    <BaseOutputPath>$(TestTempPath)\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(TestTempPath)\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
